kind: ConfigMap
apiVersion: v1
metadata:
  name: helidon-examples-todo-backend
  namespace: default
data:
  env: k8s
  services: |-
    zipkin.host: zipkin
  cassandra: |-
    servers:
      - host: helidon-examples-todo-cassandra
        port: 9042